# Configurable default values for TFSandbox
# These values can be overridden with environment variables.
# See comments in lib/tfsandbox.rb for more info.
---
:url: http://tst.ole.kuali.org/
:docstore_url: http://tst.docstore.ole.kuali.org/
:headless?: true
:default_wait: 30
